REDIS_PASSWORD=YourRedisPasswordHere123
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_URL=redis://:YourRedisPasswordHere123@redis:6379
POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=YourPostgresPasswordHere123
RAILS_MAX_THREADS=8
RAILS_SERVER_PROCESSES=2
ENABLE_WAIT_RESULT=true
DISABLE_SANDBOX=true